// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWVvtDM7nOE_uekTWj5iGqPvNhPEo91Bs',
    appId: '1:108859062606:android:9dae483af644e549',
    messagingSenderId: '108859062606',
    projectId: 'irish-bus-real-time-253da',
    databaseURL: 'https://irish-bus-real-time-253da.firebaseio.com',
    storageBucket: 'irish-bus-real-time-253da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoPlj-yEZBkbHf5HwaAQSJxsdDGGewqoQ',
    appId: '1:108859062606:ios:d62ada5861d40349',
    messagingSenderId: '108859062606',
    projectId: 'irish-bus-real-time-253da',
    databaseURL: 'https://irish-bus-real-time-253da.firebaseio.com',
    storageBucket: 'irish-bus-real-time-253da.appspot.com',
    androidClientId: '108859062606-6hnih9pqh5sgl7dcs5iicehkpmgtj0lj.apps.googleusercontent.com',
    iosClientId: '108859062606-vaod4n1ktg0sj3f9mhjhglomg3v7sbkn.apps.googleusercontent.com',
    iosBundleId: 'com.gavinmcdonald.IrishBusRealTime',
  );
}
